/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author migue
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtn_c1 = new javax.swing.JRadioButton();
        jbtn_c2 = new javax.swing.JRadioButton();
        jbtn_c3 = new javax.swing.JRadioButton();
        jbtn_consultar = new javax.swing.JButton();
        jlbl_ventascajero = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbperfil = new javax.swing.JComboBox<>();
        jbtn_crearpdf = new javax.swing.JButton();
        jlbl_ventastotales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Supermercado Multinivel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Ventas?", jPanel1);

        jLabel2.setText("Seleccione cajero a consultar: ");

        buttonGroup1.add(jbtn_c1);
        jbtn_c1.setText("Cajero 1");
        jbtn_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_c1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jbtn_c2);
        jbtn_c2.setText("Cajero 2");

        buttonGroup1.add(jbtn_c3);
        jbtn_c3.setText("Cajero 3");

        jbtn_consultar.setText("Consultar");

        jlbl_ventascajero.setText("Ventas generadas por el cajero:                           ");

        jLabel4.setText("Consultar desde perfil:");

        jcbperfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbperfilActionPerformed(evt);
            }
        });

        jbtn_crearpdf.setText("Crear PDF");

        jlbl_ventastotales.setText("Ventas totales del dia:                                                             ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_ventascajero)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcbperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtn_c1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtn_c2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn_c3))
                            .addComponent(jlbl_ventastotales)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_crearpdf)
                            .addComponent(jbtn_consultar))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jbtn_c1)
                    .addComponent(jbtn_c2)
                    .addComponent(jbtn_c3))
                .addGap(18, 18, 18)
                .addComponent(jbtn_consultar)
                .addGap(13, 13, 13)
                .addComponent(jlbl_ventascajero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jlbl_ventastotales)
                .addGap(32, 32, 32)
                .addComponent(jbtn_crearpdf)
                .addGap(16, 16, 16))
        );

        jTabbedPane5.addTab("Informes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_c1ActionPerformed

    private void jcbperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbperfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbperfilActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JRadioButton jbtn_c1;
    private javax.swing.JRadioButton jbtn_c2;
    private javax.swing.JRadioButton jbtn_c3;
    private javax.swing.JButton jbtn_consultar;
    private javax.swing.JButton jbtn_crearpdf;
    private javax.swing.JComboBox<String> jcbperfil;
    private javax.swing.JLabel jlbl_ventascajero;
    private javax.swing.JLabel jlbl_ventastotales;
    // End of variables declaration//GEN-END:variables

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JRadioButton getJbtn_c1() {
        return jbtn_c1;
    }

    public void setJbtn_c1(JRadioButton jbtn_c1) {
        this.jbtn_c1 = jbtn_c1;
    }

    public JRadioButton getJbtn_c2() {
        return jbtn_c2;
    }

    public void setJbtn_c2(JRadioButton jbtn_c2) {
        this.jbtn_c2 = jbtn_c2;
    }

    public JRadioButton getJbtn_c3() {
        return jbtn_c3;
    }

    public void setJbtn_c3(JRadioButton jbtn_c3) {
        this.jbtn_c3 = jbtn_c3;
    }

    public JButton getJbtn_consultar() {
        return jbtn_consultar;
    }

    public void setJbtn_consultar(JButton jbtn_consultar) {
        this.jbtn_consultar = jbtn_consultar;
    }

    public JButton getJbtn_crearpdf() {
        return jbtn_crearpdf;
    }

    public void setJbtn_crearpdf(JButton jbtn_crearpdf) {
        this.jbtn_crearpdf = jbtn_crearpdf;
    }

    public JComboBox<String> getJcbperfil() {
        return jcbperfil;
    }

    public void setJcbperfil(JComboBox<String> jcbperfil) {
        this.jcbperfil = jcbperfil;
    }

    public JLabel getJlbl_ventascajero() {
        return jlbl_ventascajero;
    }

    public void setJlbl_ventascajero(JLabel jlbl_ventascajero) {
        this.jlbl_ventascajero = jlbl_ventascajero;
    }

    public JLabel getJlbl_ventastotales() {
        return jlbl_ventastotales;
    }

    public void setJlbl_ventastotales(JLabel jlbl_ventastotales) {
        this.jlbl_ventastotales = jlbl_ventastotales;
    }

    
}

